insert into community(mbr_id, com_category, com_title, com_content) values ('test1', '정보', '재영이 멍충이', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test2', '일상', '테스트2', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test3', '질문', '테스트3', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test4', '일상', '테스트4', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test5', '정보', '테스트5', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test6', '질문', '테스트6', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test7', '일상', '테스트7', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test8', '일상', '테스트8', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test9', '정보', '테스트9', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test10', '질문', '테스트10', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test11', '일상', '테스트11', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test12', '정보', '테스트12', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test13', '질문', '테스트13', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test14', '일상', '테스트14', '하하하');
insert into community(mbr_id, com_category, com_title, com_content) values ('test15', '정보', '테스트15', '하하하');